// Jest Snapshot v1, https://jestjs.io/docs/snapshot-testing

exports[`print correct error message with nested test definitions inside describe 1`] = `
"FAIL __tests__/nestedTestWithinDescribe.js
  in describe
    ✕ outer test

  ● in describe › outer test

    Tests cannot be nested. Test "inner test" cannot run because it is nested within "outer test".

      14 |     expect(getTruthy()).toBeTruthy();
      15 |
    > 16 |     test('inner test', () => {
         |     ^
      17 |       expect(getTruthy()).toBeTruthy();
      18 |     });
      19 |   });

      at Object.test (__tests__/nestedTestWithinDescribe.js:16:5)"
`;

exports[`print correct error message with nested test definitions outside describe 1`] = `
"FAIL __tests__/nestedTestOutsideDescribe.js
  ✕ outer test

  ● outer test

    Tests cannot be nested. Test "inner test" cannot run because it is nested within "outer test".

      13 |   expect(getTruthy()).toBeTruthy();
      14 |
    > 15 |   test('inner test', () => {
         |   ^
      16 |     expect(getTruthy()).toBe('This test should not have run');
      17 |   });
      18 | });

      at Object.test (__tests__/nestedTestOutsideDescribe.js:15:3)"
`;
